version: '2.2'
services:
  web:
    image: nginx
    ports:
      - "6061:6061"
      - "6062:6062"
      - "6063:6063"
    container_name: "web"
    restart: always
    mem_limit: 256m
    cpus: 2
    environment:
      TZ : "Asia/Shanghai"
    networks:
      - net
    volumes: 
      - ./web:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
networks:
  net:
    driver: bridge