version: '2'
services:
  web1:
    image: nginx
    ports:
      - "6061:80"
    container_name: "web1"
    restart: always
    networks:
      - net
    volumes: 
      - ./6061:/usr/share/nginx/html
  web2:
    image: nginx
    ports:
      - "6062:80"
    container_name: "web2"
    restart: always
    networks:
      - net
    volumes: 
      - ./6062/web:/usr/share/nginx/html
      - ./6062/conf.d:/etc/nginx/conf.d
  web3:
    image: nginx
    ports:
      - "6063:80"
    container_name: "web3"
    restart: always
    networks:
      - net
    volumes: 
      - ./6063/web:/usr/share/nginx/html
      - ./6063/conf.d:/etc/nginx/conf.d
networks:
  net:
    driver: bridge