version: '3.7'
services:
  web1:
    image: nginx
    ports:
      - "6061:80"
    container_name: "web1"
    restart: always
    networks:
      - dev
    volumes: 
      - ./6061/web:/usr/share/nginx/html
      - ./6061/conf.d:/etc/nginx/conf.d
  web2:
    image: nginx
    ports:
      - "6062:80"
    container_name: "web2"
    restart: always
    networks:
      - dev
    volumes: 
      - ./6062:/usr/share/nginx/html
networks:
  dev:
    driver: bridge